= Mi blog (¿y por qué empezó?)

:hp-tags: Ocio

Desde hace mucho tiempo me topé con la gana de escribir un blog, pero hacerlo personalizado, ya había encontrado otras páginas para armar un blog pero ninguno me llamaba la atención, además, como programador quise hacerlo yo mismo (o más o menos) para entretenerme y aprender un poco, esa frase de "Perder el tiempo en algo que te gusta no cuenta como perder el tiempo." resultó válida. También por si a alguien se le apetece conversar, discutir, expresarse también cada post tiene la opción de comentar y así interactúo con gente, siempre se me hace agradable saber los puntos de vista de los demás.


Y con estas palabras empiezo lo que es una parte de mí que siempre quise expresar. Muchas veces me hallo en discuciones conmigo mismo y quiero decirlo a voz alta pero no hay con quién, o simplemente me reprimo y no lo digo y pueda ser que esto me funcione como "terapia", lo cual pienso que es absurdo, pero al final lo único que quiero es expresarme y darme a conocer, muchas personas no saben ni quien soy y aquí voy a dejar pedazos de mí en cada palabra que escriba.  
