= Los Finales Felices

En muy pocas ocasiones he tenido el gusto de ver una película con un final que no sea el perfecto y solapado "...Y vivieron felices para siempre.", probablemente porque a la gente no le gustaría, y si conocés bien esta sociedad tenés claro que para conseguir popularidad y que la gente te note hay que hacer lo que a ellos les gusta. Incluso, ya hasta se puede asumir qué es lo que va a pasar: El beso de la reconciliación, los amigos que se volvieron enemigos y que al final se unen otra vez, cuando los planetas se alinean y sucede lo imposible para que el malo pierda, no sin antes el clímax del desenlace (que el final sea el perfecto momento que todos esperan no le quita lo interesante a una película, lo admito). 

Y el colmo llega, cuando hacen una película basada en un libro y adaptan la historia para que sea "para todo público" o quepa en 120 minutos, no hay blasfemia literaria más grande que eso (y no creo ser el único que piensa eso). Y luego, si hablamos de los finales abiertos creo que podría escribir un testamento existencialista solo de eso, pero hoy no hay inspiración.

:imagen:

Aún así, disfruto de las películas, incluso de las románticas/pussy/maricas, tampoco soy una máquina sin sentimientos (aunque a veces lo parezca), creo que lloro más con las películas que pensando en mi futuro, además tengo la dicha que las películas que me recomiendan son muy buenas y que por varias situaciones del destino le tomé gusto a las películas viejas. No soy un grán cinéfilo, los días que me siento a ver una película son esporádicos y contados, si no es que por pura casualidad mientras estoy en la mesa comiendo pasan una película random en la televisión y me quedo entretenido. Por lo que si tienen una película recomendable en mente, acepto sugerencias. 

%D%