= El hijo de puta

¿Cómo puedo llamarlo si no es así? Y no me culpo,
sin embargo podría evitarlo. Es un maldito hijo de
puta que vende falsas esperanzas a almas rotas.
¿Quién lo dice? Yo, el que se dice saberse todas
el señor perfecto, el que cree ser mejor que todos
a conveniencia.

Maldito hijo de puta, su nombre es como un fantasma
que me persigue a todos lados y me sorprende cuando
menos me lo espero, me invade y me carcome 
la existencia sin poder hacer nada al respecto.

¿Culpa de quién? Hay culpables sin embargo no soy
el juez para dictar una sentencia permanente, 
solo soy una victima de dos, esperando olvidarlo todo y
enterrarlo de una maldita vez sin tener que 
pensar en todo lo que pasó y fue, y aún así
sabiendo yo la verdad y que me mientan a la cara.

"Hay que dejarlo ir, hay que olvidarlo, deja de pensar en eso"
Todo eso te dicen y suena tan fácil decirlo pero tan 
difícil e imposible ponerlo en práctica, menos
conmigo, una persona conflictiva, que se sabotea
a si misma y en extremo masoquista que prefiere
apuñalarse otra y otra vez con el mismo recuerdo
en vez de dejarlo de lado, disfrutando ver como se
me sangra la existencia.

Tal vez no soy tan maduro como pensaba, y reconocerlo
sea el primer paso para cambiar y madurar de verdad,
mientras tanto todo me parece tan desabrido, tan hostil
y tan oscuro, no estoy seguro si podré seguir confiando.

Sos un hijo de puta, y te odio.


