= Quisiera

Quisiera dejar de ser el único que vive en memorias que nunca volverán y quedarán enterradas para siempre en el olvido. Quisiera dejar de lanzarme en el mismo precipicio oscuro que me sumerge en agitadas aguas frías y solitarias, pensando que quizá, tan solo quizá, la próxima vez que me lance las aguas estarán calmas y tibias. 

Quisiera poder tener la capacidad de no volver a saber de ti, de borrarte completamente de mi existencia manchada y adolorida para poder apreciar los verdaderos cielos despejados que me esperan en el horizonte. 

Quisiera dejar de ser tan patético, dejar de desangrarme en silencio para no obtener nada, quisiera dejar de intentar renunciar a mi identidad y engañarme a mí mismo que si dejo de ser yo, tal vez todo estará mejor, y que tal vez así dejarías de odiarme.

Quisiera poder apreciar mi canción favorita sin pensarte, creyendo que se escucharía mejor con el ruido de la lluvia, sin saber que el silencio la apreciaría con mis callados sollozos y el ruido esporádico de dos lágrimas cayendo sobre mi almohada.

Solo, quisiera dejar creer que la próxima vez será diferente. Quisiera dejar de pensar que cambiarías, que yo cambiaría, que todo cambiaría, quisiera pensar 